#define TUP_PORT_BAUDRATE 115200u
#define TUP_RX_BUF_SIZE_BYTES 128u
#define TUP_SYN_TIMEOUT_MS 1000u
#define TUP_DATA_TIMEOUT_MS 5000u
#define TUP_TRY_COUNT 5u
#define TUP_RETRY_PAUSE_MS 2000u
#define TUP_FLUSH_DURATION_MS 500u

#define TUP_TASK_STACK_LEN 128
#define TUP_TASK_PRIORITY 40

#define APP_TASK_STACK_LEN 128
#define APP_TASK_PRIORITY 24
